;;; Example Cask file

(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")

(package-file "example.el")

(files "example.el")

;; Development
(development
 (depends-on "cask")
 ;; unit tests
 (depends-on "ert")
 (depends-on "ert-runner"))
